### PR TITLE
Merge pull request #1 from rasfyah/patch-1

### PR DESCRIPTION
**Pull request by Seraph08**

### CODE REVIEW

**Comment by Seraph08** [comment]
add rus translations for Notification slider setting

**Comment by Grarak** [comment]
Please don't submit translations

**Comment by ihor-sviziev** [comment]
@Seraph08 push these changes to CM Code Gerrit: http://review.cyanogenmod.org/ . Then your changes will be merged to official repo

**Comment by Grarak** [comment]
@ihor-sviziev no they won't merge translations. They go to crowdin

**Comment by ihor-sviziev** [comment]
Ah, ok. Sorry for confusing

**Comment by Seraph08** [comment]
@Grarak ok my bad. @ihor-sviziev agreed, confusing.

**Pull request closed without merging**
